version: '3.8'

services:
  mcp-as-a-judge:
    image: ghcr.io/hepivax/mcp-as-a-judge:latest
    container_name: mcp-as-a-judge
    environment:
      - LOG_LEVEL=INFO
      - DEBUG=false
    restart: unless-stopped
    stdin_open: true
    tty: true
    profiles:
      - production

  # Development service - builds from source
  mcp-as-a-judge-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    container_name: mcp-as-a-judge-dev
    environment:
      - LOG_LEVEL=DEBUG
      - DEBUG=true
      - DEVELOPMENT_MODE=true
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./.env:/app/.env
    command: ["uv", "run", "src/mcp_as_a_judge/server.py"]
    restart: "no"
    stdin_open: true
    tty: true
    profiles:
      - development




